portfoliosite/PortfolioDatabase/urls.py
from . import views
from django.urls import path

app_name = 'PortfolioDatabase'
urlpatterns = [
    path('home/', views.home, name="home"),
    path('hobbies/', views.hobbies, name="hobbies"),
    path('hobbies/<int:hobby_id>', views.hobby_detail, name="hobbyDetail"),
    path('portfolios/', views.portfolios, name="portfolios"),
    path('portfolios/add', views.create_portfolio, name="create_portfolio"),
    path('portfolios/update/<int:portfolio_id>', views.update_portfolio, name="update_portfolio"),
    path('portfolios/delete/<int:portfolio_id>', views.delete_portfolio, name="delete_portfolio"),
    path('portfolios/<int:portfolio_id>', views.portfolio_detail, name="portfolioDetail"),
    path('contact/', views.contact, name="contact")
]

portfoliosite/portfoliosite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PortfolioDatabase.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

portfoliosite/PortfolioDatabase/models.py
from django.db import models

# Create your models here.


class Hobby(models.Model):

    def __str__(self):
        return self.hobby_name

    hobby_name = models.CharField(max_length=200)
    hobby_desc = models.CharField(max_length=200)
    hobby_image = models.CharField(max_length=500, default="https://cdn.iconscout.com/icon/premium/png-256-thumb/hobby-6-1100854.png")


class Portfolio(models.Model):

    def __str__(self):
        return self.portfolio_name

    portfolio_name = models.CharField(max_length=200)
    portfolio_desc = models.CharField(max_length=200)
    portfolio_image = models.CharField(max_length=500, default="https://cdn.iconscout.com/icon/premium/png-256-thumb/notebook-1717991-1459674.png")


class Contact(models.Model):

    def __str__(self):
        return self.contact_name

    contact_name = models.CharField(max_length=200)
    contact_email = models.CharField(max_length=300)
    contact_message = models.TextField(max_length=1000)

portfoliosite/users/models.py
from django.db import models

# Create your models here.

portfoliosite/PortfolioDatabase/forms.py
from django import forms
from .models import Portfolio, Contact


class PortfolioForm(forms.ModelForm):
    class Meta:
        model = Portfolio
        fields = ['portfolio_name', 'portfolio_desc', 'portfolio_image']


class ContactForm(forms.ModelForm):
    contact_name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    contact_email = forms.EmailField(max_length=300, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    contact_message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Contact
        fields = ('contact_name', 'contact_email', 'contact_message')

portfoliosite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

portfoliosite/PortfolioDatabase/views.py
from django.shortcuts import render, redirect
from .models import Hobby
from .models import Portfolio, Contact
from .forms import PortfolioForm, ContactForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


# Create your views here.
def home(request):
    context = {}
    return render(request, 'PortfolioDatabase/home.html', context)


def hobbies(request):
    hobby_list = Hobby.objects.all()
    context = {
        'hobby_list': hobby_list,
    }
    return render(request, 'PortfolioDatabase/hobbies.html', context)


def hobby_detail(request, hobby_id):
    hobby = Hobby.objects.get(pk=hobby_id)
    context = {
        'hobby': hobby
    }
    return render(request, 'PortfolioDatabase/hobbyDetail.html', context)


def portfolios(request):
    portfolio_list = Portfolio.objects.all()
    context = {
        'portfolio_list': portfolio_list,
    }
    return render(request, 'PortfolioDatabase/portfolios.html', context)


@login_required
def create_portfolio(request):
    form = PortfolioForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('PortfolioDatabase:portfolios')
    return render(request, 'PortfolioDatabase/portfolio-form.html', {'form': form})


@login_required
def update_portfolio(request, portfolio_id):
    portfolio = Portfolio.objects.get(id=portfolio_id)
    form = PortfolioForm(request.POST or None, instance=portfolio)
    if form.is_valid():
        form.save()
        return redirect('PortfolioDatabase:portfolios')
    return render(request, 'PortfolioDatabase/portfolio-form.html', {'form': form, 'portfolio': portfolio})


@login_required
def delete_portfolio(request, portfolio_id):
    portfolio = Portfolio.objects.get(pk=portfolio_id)
    if request.method == 'POST':
        portfolio.delete()
        return redirect('PortfolioDatabase:portfolios')
    return render(request, 'PortfolioDatabase/portfolio-delete.html', {'portfolio': portfolio})


def portfolio_detail(request, portfolio_id):
    portfolio = Portfolio.objects.get(pk=portfolio_id)
    context = {
        'portfolio': portfolio,
    }
    return render(request, 'PortfolioDatabase/portfolioDetail.html', context)


def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, f'Message Sent.')
        return redirect('PortfolioDatabase:home')
    return render(request, 'PortfolioDatabase/contact.html', {'form': form})

portfoliosite/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegistrationForm


# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}! You are logged in.')
            return redirect('users:login')
    else:
        form = RegistrationForm()
    return render(request, 'users/register.html', {'form': form})

portfoliosite/PortfolioDatabase/templates/PortfolioDatabase/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'PortfolioDatabase/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cutive">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a href="#" class="navbar-brand">Portfolio Database</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navigation">
            <ul class="navbar-nav me-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'PortfolioDatabase:home' %}">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'PortfolioDatabase:hobbies' %}">Hobbies</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'PortfolioDatabase:portfolios' %}">Portfolios</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'PortfolioDatabase:contact' %}">Contact</a>
                </li>

            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item active me-auto">
                    {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}" class="nav-link text-end">Logout</a>
                    {% else %}
                        <a href="{% url 'login' %}" class="nav-link text-end">Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>
{% if messages %}
    <div class="container">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible show" role="alert">
                {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
{% endif %}
{% block body %}
{% endblock %}
</body>
</html>

portfoliosite/PortfolioDatabase/templates/PortfolioDatabase/contact.html
{% extends 'PortfolioDatabase/base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% block body %}
    <div class="container mt-3">
        <div class="row">
            <h1 class="text-center page-title">Contact</h1>
        </div>
        <div class="row mt-2">
            <h3 class="text-center">Questions or Comments?</h3>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form }}
                            <button type="submit" class="btn btn-primary mt-3">Send Message</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                    <a class="email-link" href="mailto: williammcconnell@mail.weber.edu">williammcconnell@mail.weber.edu</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

portfoliosite/PortfolioDatabase/templates/PortfolioDatabase/hobbies.html
{% extends 'PortfolioDatabase/base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% block body %}
    <div class="container mt-3">
        <div class="row">
            <h1 class="text-center page-title">Hobbies</h1>
        </div>
        {% for hobby in hobby_list %}
            <div class="row align-items-center">
                <div class="col-md-3 offset-md-2">
                    <img class="card mt-1 zoom" height="150px" src="{{ hobby.hobby_image }}" alt="{{ hobby.hobby_name }}">
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">{{ hobby.hobby_name }}</h3>
                            <h5 class="card-text">{{ hobby.hobby_desc }}</h5>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <a href="{% url 'PortfolioDatabase:hobbyDetail' hobby.id %}" class="btn btn-success">Details</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
</body>
</html>

portfoliosite/PortfolioDatabase/templates/PortfolioDatabase/hobbyDetail.html
{% extends 'PortfolioDatabase/base.html' %}
{% block body %}
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6">
                <img src="{{ hobby.hobby_image }}" class="card mt-1" height="300px" alt="{{ hobby.hobby_name }}">
            </div>
            <div class="col-md-6">
                <h1 class="animation-typewriter">{{ hobby.hobby_name }}</h1>
                <h2>{{ hobby.hobby_desc }}</h2>
            </div>
        </div>
    </div>
{% endblock %}

portfoliosite/PortfolioDatabase/templates/PortfolioDatabase/home.html
{% extends 'PortfolioDatabase/base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% block body %}
    <div class="container mt-3">
        <div class="row">
            <h1 class="text-center page-title">Home</h1>
        </div>
        <div class="row mt-3">
            <div class="col-md-4 offset-md-1">
                <div class="card">
                    <img class="card-img-top rounded-circle" src="https://cdn.iconscout.com/icon/free/png-256/account-avatar-profile-human-man-user-30448.png">
                    <h5 class="card-header">About Me</h5>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><strong>Name:</strong> William McConnell</li>
                        <li class="list-group-item"><strong>Age:</strong> 29</li>
                        <li class="list-group-item"><strong>Email:</strong> <a class="email-link" href="mailto: williammcconnell@mail.weber.edu">williammcconnell@mail.weber.edu</a></li>
                        <li class="list-group-item"><strong>Degree:</strong> Computer Science</li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Welcome to my home page</h5>
                        <p class="card-text">My name is William McConnell. I am a 29-year-old CS student looking to graduate and move into the work force as of the end of this spring.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

portfoliosite/PortfolioDatabase/templates/PortfolioDatabase/portfolio-delete.html
{% extends 'PortfolioDatabase/base.html' %}
{% block body %}
    <div class="container mt-4">
        <form method="POST">
            {% csrf_token %}
            <h2>Are you sure you want to delete {{ portfolio.portfolio_name }}?</h2>
            <button type="submit" class="btn btn-danger">Confirm</button>
        </form>
    </div>
{% endblock %}

portfoliosite/PortfolioDatabase/templates/PortfolioDatabase/portfolio-form.html
{% extends 'PortfolioDatabase/base.html' %}
{% block body %}
    <div class="container mt-4">
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

portfoliosite/PortfolioDatabase/templates/PortfolioDatabase/portfolioDetail.html
{% extends 'PortfolioDatabase/base.html' %}
{% block body %}
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6">
                <img src="{{ portfolio.portfolio_image }}" class="card mt-1" height="300px" alt="{{ portfolio.portfolio_name }}">
            </div>
            <div class="col-md-6">
                <h1 class="animation-typewriter">{{ portfolio.portfolio_name }}</h1>
                <h2>{{ portfolio.portfolio_desc }}</h2>
                {% if user.is_authenticated %}
                    <a href="{% url 'PortfolioDatabase:delete_portfolio' portfolio.id %}" class="btn btn-danger">Delete</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

portfoliosite/PortfolioDatabase/templates/PortfolioDatabase/portfolios.html
{% extends 'PortfolioDatabase/base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% block body %}
    <div class="container mt-3">
        <div class="row">
            <h1 class="text-center page-title">Portfolios</h1>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-5">
                <a href="{% url 'PortfolioDatabase:create_portfolio' %}" class="btn btn-warning">+ Create Portfolio</a>
            </div>
        </div>
        {% for portfolio in portfolio_list %}
            <div class="row align-items-center">
                <div class="col-md-3 offset-md-2">
                    <img class="card mt-1 zoom" height="150px" src="{{ portfolio.portfolio_image }}" alt="{{ portfolio.portfolio_name }}">
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">{{ portfolio.portfolio_name }}</h3>
                            <h5 class="card-text">{{ portfolio.portfolio_desc }}</h5>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <a href="{% url 'PortfolioDatabase:portfolioDetail' portfolio.id %}" class="btn btn-success">Details</a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'PortfolioDatabase:update_portfolio' portfolio.id %}" class="btn btn-primary">Edit</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
</body>
</html>

portfoliosite/users/templates/users/login.html
{% extends 'PortfolioDatabase/base.html' %}
{% block body %}
    <div class="container mt-4">
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
{% endblock %}

portfoliosite/users/templates/users/logout.html
{% extends 'PortfolioDatabase/base.html' %}
{% block body %}
    <div class="container mt-4">
        <h1>You have been logged out.</h1>
        <a href="{% url 'PortfolioDatabase:home' %}" class="btn btn-success">Okay</a>
    </div>
{% endblock %}

portfoliosite/users/templates/users/register.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Signup</button>
</form>